# 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑
# 🛑 THIS IS AN AUTOGENERATED FILE - DO NOT EDIT DIRECTLY 🛑
# 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑
from __future__ import annotations

import json
import os
from typing import TYPE_CHECKING, TypedDict, cast

if TYPE_CHECKING:
    from typing import NotRequired


class Env(TypedDict):
    """Coerced env schema (matches varlock coercion) — values are typed, not raw strings."""
    EXAMPLE_ITEM: str  # example env variable injected by `varlock init` ⚠️ DELETE THIS ITEM! ⚠️
    GOOGLE_API_KEY: NotRequired[str]
    GROQ_API_KEY: NotRequired[str]
    LANGSMITH_API_KEY: NotRequired[str]


# Keys whose values are sensitive — use this to build your own redaction / leak-scanning.
SENSITIVE_KEYS: frozenset[str] = frozenset({"EXAMPLE_ITEM", "GOOGLE_API_KEY", "GROQ_API_KEY", "LANGSMITH_API_KEY"})


def load_env() -> Env:
    """Parse the `__VARLOCK_ENV` blob (injected by `varlock run`) into typed, coerced values."""
    blob = os.environ.get("__VARLOCK_ENV")
    if not blob:
        raise RuntimeError("__VARLOCK_ENV is not set — run your program via `varlock run` (note: `--inject vars` omits the blob this module needs)")
    if blob.startswith("varlock:v1:"):
        raise RuntimeError("__VARLOCK_ENV is encrypted and this generated module cannot decrypt it — disable @encryptInjectedEnv for processes using a generated env module")
    graph = json.loads(blob)
    # unset optional keys are omitted from the blob (no "value"), so skip them here —
    # matches the TypedDict `NotRequired` contract (key absent, not present-as-None)
    return cast(
        Env,
        {key: entry["value"] for key, entry in graph["config"].items() if "value" in entry},
    )
